### ISSUE TITLE
Fix Incorrect Directory Placement of Documentation Files

### ISSUE THREAD

**Issue by tingxiang-ji** [510-s-Mickey/units_converter_extension#11]
## Describe the bug

Some documentation files are incorrectly located in the .github directory instead of the intended docs directory.

## To Reproduce

1. Navigate to the .github directory.
2. Observe misplaced documentation files (e.g., .md files).

## Expected behavior
All documentation files (e.g., .md files) should be located in the docs directory for better organization and accessibility.

**Comment by HuiSunNCSU** [comment]
Solved
