### ISSUE TITLE
UpdateReadme

### ISSUE THREAD

**Issue by LUfansx** [510-s-Mickey/units_converter_extension#20]
Update the project Readme.md

**Comment by LUfansx** [comment]
<img width="507" alt="image" src="https://github.com/user-attachments/assets/d5bf4715-46b9-4d7d-afeb-511365b96190">

**Comment by LUfansx** [comment]
<img width="504" alt="image" src="https://github.com/user-attachments/assets/d69a24f7-5610-40f9-9add-f17ad6e07985">

**Comment by LUfansx** [comment]
<img width="506" alt="image" src="https://github.com/user-attachments/assets/b9576171-e2f2-47c5-adde-359951068e4c">

**Comment by LUfansx** [comment]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/b4cdf44b-0236-4860-aede-cf512f95e8e6">

**Comment by LUfansx** [comment]
<img width="501" alt="image" src="https://github.com/user-attachments/assets/8035d45f-58e5-4267-b981-4eaf0398a83e">

**Comment by HuiSunNCSU** [comment]
Solved

**Comment by LUfansx** [comment]
![image](https://github.com/user-attachments/assets/0fc774ab-ff80-4b2d-830c-2ca6899bb93f)

**Comment by LUfansx** [comment]
![image](https://github.com/user-attachments/assets/ad71e74c-382e-488b-bb19-d2a6f27d1213)

**Comment by LUfansx** [comment]
![image](https://github.com/user-attachments/assets/fb30a6c6-1cbf-41c3-a24e-c07826303e4e)
